stages:
  - build
  - test



build:linux:
  stage: build
  before_script:
    - apt update -qy
    - apt install build-essential qt5-qmake qtwebengine5-dev -qy
  script:
    - qmake qt-kiosk.pro
    - make
  tags:
    - debian

  artifacts:
    paths:
      - qt-kiosk
    expire_in: 1d

    
test:linux:
  stage: test
  before_script:
    - apt install libqt5webenginewidgets5 -qy
  script:
    - ./qt-kiosk -h
  dependencies:
    - build:linux
  tags:
    - debian
