stages:
  - build
  - package
  - deploy


build:debian:x86-64:
  stage: build
  before_script:
    - apt update -qy
    - apt install build-essential cmake libxkbcommon-dev qt6-base-dev qt6-webengine-dev qt6-webengine-dev-tools libqt6webenginewidgets6 libqt6webenginecore6-bin -qy
  script:
    - cmake .
    - make
  tags:
    - debian

  artifacts:
    paths:
      - qiosk
    expire_in: 1d

package:debian:x86-64:
  stage: package
  script:
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake libxkbcommon-dev qt6-base-dev qt6-webengine-dev qt6-webengine-dev-tools libqt6webenginewidgets6 libqt6webenginecore6-bin -qy
    - dpkg-buildpackage -us -uc
    - mv ../qiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qiosk*.deb
    expire_in: 1d


package:debian:x86-64-qt5:
  stage: package
  script:
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake qtwebengine5-dev -qy
    - mv debian/control debian/control.old && mv debian/control-qt5 debian/control
    - dpkg-buildpackage -us -uc
    - mv ../qt5-qiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qt5-qiosk*.deb
    expire_in: 1d
    
    
package:debian:arm64:
  stage: package
  script:
    - dpkg --add-architecture arm64
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake crossbuild-essential-arm64 qt6-webengine-dev:arm64 -qy
    - export CONFIG_SITE=/etc/dpkg-cross/cross-config.arm64  
    - export DEB_BUILD_OPTIONS=nocheck 
    - dpkg-buildpackage -aarm64 -Pcross,nocheck -us -uc
    - mv ../qiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qiosk*.deb
    expire_in: 1d

package:debian:armhf:
  stage: package
  script:
    - dpkg --add-architecture armhf
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake crossbuild-essential-armhf qt6-webengine-dev:armhf -qy
    - export CONFIG_SITE=/etc/dpkg-cross/cross-config.armhf  
    - export DEB_BUILD_OPTIONS=nocheck 
    - dpkg-buildpackage -aarmhf -Pcross,nocheck -us -uc
    - mv ../qiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qiosk*.deb
    expire_in: 1d

package:debian:armhf-qt5:
  stage: package
  script:
    - dpkg --add-architecture armhf
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake crossbuild-essential-armhf qtwebengine5-dev:armhf -qy
    - mv debian/control debian/control.old && mv debian/control-qt5 debian/control
    - export CONFIG_SITE=/etc/dpkg-cross/cross-config.armhf  
    - export DEB_BUILD_OPTIONS=nocheck 
    - dpkg-buildpackage -aarmhf -Pcross,nocheck -us -uc
    - mv ../qt5-qiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qt5-qiosk*.deb
    expire_in: 1d


package:archlinux:x86-64:
  stage: package
  script:
    - pacman -Syu sudo binutils fakeroot qt6-webengine qt6-virtualkeyboard cmake gcc make --noconfirm
    - useradd -m -G users -s /bin/bash package
    - chown -R package:users archlinux
    - cd archlinux
    - sudo -H -u package makepkg -f
  tags:
    - archlinux

  artifacts:
    paths:
      - archlinux/qiosk*
    expire_in: 1d
    
package:archlinux:armv7h:
  stage: package
  script:
    - sudo pacman -Sy binutils fakeroot qt5-webengine qt5-virtualkeyboard cmake gcc make --noconfirm
    - cd archlinux
    - makepkg -f -p PKGBUILD-qt5
  tags:
    - archlinux-arm7

  artifacts:
    paths:
      - archlinux/qiosk*
    expire_in: 1d


package:archlinux:aarch64:
  stage: package
  script:
    - sudo pacman -Syu binutils fakeroot qt6-webengine qt6-virtualkeyboard cmake gcc make --noconfirm
    - cd archlinux
    - makepkg -f
  tags:
    - archlinux-aarch64

  artifacts:
    paths:
      - archlinux/qiosk*
    expire_in: 1d

repoupdate:
  stage: deploy
  before_script:
    # SSH
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - apt-get update -y
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/www/arch/pub/x86_64/qiosk*.pkg.tar.*'
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/www/arch/pub/armv7h/qiosk*.pkg.tar.*'
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/www/arch/pub/aarch64/qiosk*.pkg.tar.*'
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/cache/deb/pub/all/qiosk*.deb'
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/cache/deb/pub/all/qt5-qiosk*.deb'
    - scp archlinux/qiosk-*-x86_64.pkg.tar.* www-data@repository:/var/www/repository.salamek.cz/www/arch/pub/x86_64
    - scp archlinux/qiosk-*-armv7h.pkg.tar.* www-data@repository:/var/www/repository.salamek.cz/www/arch/pub/armv7h
    - scp archlinux/qiosk-*-aarch64.pkg.tar.* www-data@repository:/var/www/repository.salamek.cz/www/arch/pub/aarch64
    - scp qiosk*.deb www-data@repository:/var/www/repository.salamek.cz/cache/deb/pub/all
    - scp qt5-qiosk*.deb www-data@repository:/var/www/repository.salamek.cz/cache/deb/pub/all
    - ssh www-data@repository '/var/www/repository.salamek.cz/deb-pub-update.sh'
    - ssh www-data@repository '/var/www/repository.salamek.cz/arch-pub-update.sh'
  
  dependencies:
    - package:debian:arm64
    - package:debian:armhf
    - package:debian:armhf-qt5
    - package:debian:x86-64
    - package:debian:x86-64-qt5
    - package:archlinux:x86-64
    - package:archlinux:armv7h
    - package:archlinux:aarch64
  tags:
    - debian
  only:
    - tags
