stages:
  - build
  - package
  - deploy


build:debian:x86-64:
  stage: build
  before_script:
    - apt update -qy
    - apt install build-essential cmake qtwebengine5-dev -qy
  script:
    - cmake .
    - make
  tags:
    - debian

  artifacts:
    paths:
      - qiosk
    expire_in: 1d

package:debian:x86-64:
  stage: package
  script:
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake qtwebengine5-dev -qy
    - dpkg-buildpackage -us -uc
    - mv ../qiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qiosk*.deb
    expire_in: 1d
    
    
package:debian:x86-64-qt6:
  stage: package
  script:
    - echo "deb http://deb.debian.org/debian bullseye-backports main contrib non-free" | tee /etc/apt/sources.list.d/backports.list
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake -qy
    - apt install libqt6* libqt6webenginewidgets6 -t bullseye-backports -qy
    # Rename package to qt6-qiosk
    - mv debian/control debian/control.old && mv debian/control-qt6 debian/control
    - dpkg-buildpackage -us -uc
    - mv ../qt6-qiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qiosk*.deb
    expire_in: 1d


package:debian:arm64:
  stage: package
  script:
    - dpkg --add-architecture arm64
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake crossbuild-essential-arm64 qtwebengine5-dev:arm64 -qy
    - export CONFIG_SITE=/etc/dpkg-cross/cross-config.arm64  
    - export DEB_BUILD_OPTIONS=nocheck 
    - dpkg-buildpackage -aarm64 -Pcross,nocheck -us -uc
    - mv ../qiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qiosk*.deb
    expire_in: 1d

package:debian:armhf:
  stage: package
  script:
    - dpkg --add-architecture armhf
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake crossbuild-essential-armhf qtwebengine5-dev:armhf -qy
    - export CONFIG_SITE=/etc/dpkg-cross/cross-config.armhf  
    - export DEB_BUILD_OPTIONS=nocheck 
    - dpkg-buildpackage -aarmhf -Pcross,nocheck -us -uc
    - mv ../qiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qiosk*.deb
    expire_in: 1d


package:archlinux:x86-64:
  stage: package
  script:
    - pacman -Sy sudo binutils fakeroot qt5-webengine qt5-virtualkeyboard cmake gcc make --noconfirm
    - useradd -m -G users -s /bin/bash package
    - chown -R package:users archlinux
    - cd archlinux
    - sudo -H -u package makepkg -f
  tags:
    - archlinux

  artifacts:
    paths:
      - archlinux/qiosk*
    expire_in: 1d

repoupdate:
  stage: deploy
  before_script:
    # SSH
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - apt-get update -y
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/www/arch/pub/x86_64/qiosk*.pkg.tar.zst'
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/cache/deb/pub/all/qiosk*.deb'
    - scp archlinux/qiosk*.pkg.tar.zst www-data@repository:/var/www/repository.salamek.cz/www/arch/pub/x86_64
    - scp qiosk*.deb www-data@repository:/var/www/repository.salamek.cz/cache/deb/pub/all
    - ssh www-data@repository '/var/www/repository.salamek.cz/deb-pub-update.sh'
    - ssh www-data@repository '/var/www/repository.salamek.cz/arch-pub-update.sh'
  
  dependencies:
    - package:debian:arm64
    - package:debian:armhf
    - package:debian:x86-64
    - package:archlinux:x86-64
  tags:
    - debian
  only:
    - tags
