stages:
  - build
  - package



build:linux:x86-64:
  stage: build
  before_script:
    - apt update -qy
    - apt install build-essential qt5-qmake qtwebengine5-dev -qy
  script:
    - qmake qt-kiosk.pro
    - make
  tags:
    - debian

  artifacts:
    paths:
      - qt-kiosk
    expire_in: 1d

build:linux:arm64:
  stage: build
  before_script:
    - apt update -qy
    - apt install build-essential qt5-qmake qtwebengine5-dev -qy
  script:
    - qmake qt-kiosk.pro
    - make
  tags:
    - debian-arm64

  artifacts:
    paths:
      - qt-kiosk
    expire_in: 1d

package:debian:x86-64:
  stage: package
  script:
    - apt update -qy
    - apt install dh-make -qy
    - dpkg-buildpackage
  dependencies:
    - build:linux:x86-64
  tags:
    - debian

  artifacts:
    paths:
      - qt-kiosk*.deb
    expire_in: 1d





#test:linux:
#  stage: test
#  before_script:
#    - apt update -qy
#    - apt install libqt5webenginewidgets5 -qy
#  script:
#    - ./qt-kiosk -h
#  dependencies:
#    - build:linux
#  tags:
#    - debian
