stages:
  - build
  - package
  - deploy


build:debian:x86-64:
  stage: build
  before_script:
    - apt update -qy
    - apt install build-essential cmake qtwebengine5-dev -qy
  script:
    - cmake .
    - make
  tags:
    - debian

  artifacts:
    paths:
      - qt-kiosk
    expire_in: 1d

package:debian:x86-64:
  stage: package
  script:
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake qtwebengine5-dev -qy
    - dpkg-buildpackage -us -uc
    - mv ../qt-kiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qt-kiosk*.deb
    expire_in: 1d


#package:debian:arm64:
#  stage: package
#  script:
#    - apt update -qy
#    - apt upgrade -qy 
#    - apt install dh-make build-essential cmake qtwebengine5-dev -qy
#    - dpkg-buildpackage -us -uc
#    - mv ../qt-kiosk*.deb .
#  tags:
#    - debian-arm64
#
#  artifacts:
#    paths:
#      - ./qt-kiosk*.deb
#    expire_in: 1d

package:debian:arm64:
  stage: package
  script:
    - dpkg --add-architecture arm64
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake crossbuild-essential-arm64 qtwebengine5-dev:arm64 -qy
    - export CONFIG_SITE=/etc/dpkg-cross/cross-config.arm64  
    - export DEB_BUILD_OPTIONS=nocheck 
    - dpkg-buildpackage -aarm64 -Pcross,nocheck -us -uc
    - mv ../qt-kiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qt-kiosk*.deb
    expire_in: 1d

package:debian:armhf:
  stage: package
  script:
    - dpkg --add-architecture armhf
    - apt update -qy
    - apt upgrade -qy 
    - apt install dh-make build-essential cmake crossbuild-essential-armhf qtwebengine5-dev:armhf -qy
    - export CONFIG_SITE=/etc/dpkg-cross/cross-config.armhf  
    - export DEB_BUILD_OPTIONS=nocheck 
    - dpkg-buildpackage -aarmhf -Pcross,nocheck -us -uc
    - mv ../qt-kiosk*.deb .
  tags:
    - debian

  artifacts:
    paths:
      - ./qt-kiosk*.deb
    expire_in: 1d


package:archlinux:x86-64:
  stage: package
  script:
    - pacman -Sy sudo binutils fakeroot qt6-webengine cmake --noconfirm
    - useradd -m -G users -s /bin/bash package
    - chown -R package:users archlinux
    - cd archlinux
    - sudo -H -u package makepkg -f
  tags:
    - archlinux

  artifacts:
    paths:
      - archlinux/qt-kiosk*
    expire_in: 1d

repoupdate:
  stage: deploy
  before_script:
    # SSH
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - apt-get update -y
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/www/arch/pub/x86_64/qt-kiosk*.pkg.tar.zst'
    - ssh www-data@repository 'rm -rf /var/www/repository.salamek.cz/cache/deb/pub/all/qt-kiosk*.deb'
    - scp archlinux/qt-kiosk*.pkg.tar.zst www-data@repository:/var/www/repository.salamek.cz/www/arch/pub/x86_64
    - scp qt-kiosk*.deb www-data@repository:/var/www/repository.salamek.cz/cache/deb/pub/all
    - ssh www-data@repository '/var/www/repository.salamek.cz/deb-pub-update.sh'
    - ssh www-data@repository '/var/www/repository.salamek.cz/arch-pub-update.sh'
  
  dependencies:
    - package:debian:arm64
    - package:debian:armhf
    - package:debian:x86-64
    - package:archlinux:x86-64
  tags:
    - debian
  #only:
  #  - tags
