#!/bin/sh
# postinst script for qt-kiosk
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
        if [ -z "$2" ]; then
            ln -sf /etc/qt-kiosk/config.json /usr/lib/qt-kiosk/config/config.production.json
            if ! systemctl is-enabled --quiet nginx; then
                systemctl enable nginx
            fi

            if ! systemctl is-active --quiet nginx; then
                systemctl restart nginx
            fi
        else
            ln -sf /etc/qt-kiosk/config.json /usr/lib/qt-kiosk/config/config.production.json
            systemctl restart nginx
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
