Document: tux-control-frontend
Title: Debian tux-control-frontend Manual
Author: <insert document author here>
Abstract: This manual describes what tux-control-frontend is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tux-control-frontend/tux-control-frontend.sgml.gz

Format: postscript
Files: /usr/share/doc/tux-control-frontend/tux-control-frontend.ps.gz

Format: text
Files: /usr/share/doc/tux-control-frontend/tux-control-frontend.text.gz

Format: HTML
Index: /usr/share/doc/tux-control-frontend/html/index.html
Files: /usr/share/doc/tux-control-frontend/html/*.html
